name: Deploy Pipeline

on:
  pull_request:
    branches:
      - test
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: test
      - run: ls
      
